apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: frenchy51/motd-api
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: configmap-killian
              key: message
